from datetime import datetime


def generate_report(user, farm_name, crop, symptoms, diagnosis):
    """
    Generates a structured text report (we'll upgrade to PDF next).
    """

    report = f"""
CROPINSIGHT FARM DIAGNOSIS REPORT
=================================

Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

Farmer ID: {user['id']}
Farm Name: {farm_name}
Crop: {crop}

---------------------------------
SYMPTOMS REPORTED
---------------------------------
{symptoms}

---------------------------------
DIAGNOSIS RESULT
---------------------------------
Disease: {diagnosis.get('disease', 'Unknown')}
Confidence: {diagnosis.get('confidence', 0)}%
Severity: {diagnosis.get('severity', 'Unknown')}

---------------------------------
RECOMMENDED ACTION
---------------------------------
Treatment: {diagnosis.get('treatment', 'Not available')}

---------------------------------
NOTE
---------------------------------
This report is generated by CropInsight AI Decision Support System.
Use as advisory guidance only.
"""

    return report
